# Site settings
title: Daniel Winkler
email: dan@danwink.com
description: > # this means to ignore newlines until "baseurl:"
  Daniel Winkler Personal Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://danwink.com" # the base hostname & protocol for your site
twitter_username: danwink
github_username:  danwinkler

# Build settings
markdown: kramdown

# Outputting
permalink: /:categories/:title/

collections:
    demos:
        output: true
    portfolio:
        output: true
